version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:14.20
    steps:
      - run:
          name: Clone backend
          command: git clone https://github.com/Poulo22/labo1_CircleCi.git
      - node/install-packages:
          pkg-manager: npm
          app-dir: ./labo1_CircleCi
      - run:
          name: Run tests
          command: |
            cd labo1_CircleCi
            npm test

  integrationFrontend:
    docker:
      - image: cimg/node:14.20
    steps:
      - run:
          name: Clone backend repo
          command: git clone https://github.com/Poulo22/labo1_CircleCi.git
      - run:
          name: Clone frontend repo
          command: git clone https://github.com/Poulo22/labo1_CircleCi_frontend.git
      - node/install-packages:
          pkg-manager: npm
          app-dir: ./labo1_CircleCi_frontend
      - run:
          name: Build frontend
          command: |
            cd labo1_CircleCi_frontend
            npm run build
      - run:
          name: Dossier public backend
          command: mkdir -p labo1_CircleCi/public
      - run:
          name: Copie Dossier public
          command: cp -R labo1_CircleCi_frontend/build/* labo1_CircleCi/public/
      - persist_to_workspace:
          root: .
          paths:
            - labo1_CircleCi

  deploiement:
    docker:
      - image: cimg/node:14.20
    steps:
      - attach_workspace:
          at: .
      - run:
          name: liste dossier backe
          command: |
            cd labo1_CircleCi
            ls -Rl

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend

